<?php

/** @var mixed[] $parameters */
/** @var object[] $queries */
/** @var int $queriesNum */
/** @var float $totalTime */

use Nettrine\DBAL\Utils\QueryUtils;
use Tracy\Dumper;
use Tracy\Helpers;

?>
<style>
	#tracy-debug td.tracy-dbal-sql {
		background: white !important
	}

	#tracy-debug .tracy-dbal-source {
		color: #999 !important
	}

	#tracy-debug .tracy-dbal tr table {
		margin: 8px 0;
		max-height: 150px;
		overflow: auto
	}
</style>

<?php if (!$queriesNum): ?>
	<h1>No queries</h1>
<?php else: ?>
	<h1>Queries:
		<?= $queriesNum ?>
		<?= $totalTime ? sprintf('%0.3f', $totalTime * 1000) : ''; ?>
	</h1>
<?php endif; ?>


<div class="tracy-inner nettrine-dbal">
	<?= Dumper::toHtml($parameters, [Dumper::COLLAPSE => TRUE]); ?>

	<?php if (count($queries)): ?>
		<table class="tracy-sortable">
			<tr>
				<th>Time&nbsp;ms</th>
				<th>SQL Statement</th>
			</tr>

			<?php foreach ($queries as $q): ?>
				<tr>
					<td>
						<?= sprintf('%0.2f', $q->duration * 1000); ?>
						<?php if (count($q->source) !== 0): ?>
							<br><a class="tracy-toggle tracy-collapsed" data-tracy-ref="^tr .nettrine-dbal-backtrace">source</a>
						<?php endif; ?>
					</td>
					<td class="tracy-dbal-sql">
						<?= QueryUtils::highlight($q->sql); ?>
						<?php if (count($q->source) !== 0): ?>
							<table class="nettrine-dbal-backtrace tracy-collapsed">
								<?php foreach ($q->source as $s): ?>
									<tr><td><?= Helpers::editorLink($s['file'], $s['line']); ?></td></tr>
								<?php endforeach; ?>
							</table>
						<?php endif; ?>
					</td>
				</tr>
			<?php endforeach; ?>

		</table>
	<?php endif; ?>
</div>
