language: php

php:
  - 7.2
  - 7.3
  - 7.4snapshot

before_install:
  # Turn off XDebug
  - phpenv config-rm xdebug.ini || return 0

install:
  # Composer
  - travis_retry composer install --no-progress --prefer-dist

script:
  # Tests
  - composer run-script tests

jobs:
  include:
    - env: title="Lowest Dependencies 7.2"
      php: 7.2
      install:
        - travis_retry composer update --no-progress --prefer-dist --prefer-lowest
      script:
        - composer run-script tests

    - stage: Quality Assurance
      php: 7.2
      script:
        - composer run-script qa

    - stage: Phpstan
      php: 7.2
      script:
        - composer run-script phpstan

    - stage: Test Coverage
      if: branch = master AND type = push
      php: 7.2
      script:
        - composer run-script coverage
      after_script:
        - composer global require php-coveralls/php-coveralls ^2.1.0
        - ~/.composer/vendor/bin/php-coveralls --verbose --config tests/.coveralls.yml

    - stage: Outdated Dependencies
      if: branch = master AND type = cron
      php: 7.2
      script:
        - composer outdated --direct --strict

  allow_failures:
    - php: 7.4snapshot
    - stage: Test Coverage

sudo: false

cache:
  directories:
    - $HOME/.composer/cache
