<?php declare(strict_types = 1);

namespace Nettrine\DBAL\Tracy;

use Doctrine\DBAL\Connection;
use Nettrine\DBAL\Utils\Formatter;
use Nettrine\DBAL\Utils\QueryUtils;
use Tracy\Helpers;

/** @var Connection $connection */
/** @var Formatter $formatter  */
/** @var int $queriesNum */
/** @var int $totalTime */
/** @var array<array{sql: string, params: mixed[], types: mixed[], duration: float }> $queries */
?>
	<style>
		#tracy-debug td.tracy-dbal-sql {
			background: white !important
		}

		#tracy-debug .tracy-dbal-source {
			color: #999 !important
		}

		#tracy-debug .tracy-dbal tr table {
			margin: 8px 0;
			max-height: 150px;
			overflow: auto
		}

		#tracy-debug .nettrine-dbal td > a.tracy-toggle::before {
			content: 'source';
		}
	</style>

	<?php if ($queriesNum === 0) { ?>
	<h1>No queries</h1>
<?php } else { ?>
	<h1>Queries:
		<?= $queriesNum ?>,
		time:
		<?= $totalTime ? sprintf('%0.3f', $totalTime * 1000) : ''; ?> ms
	</h1>
	<div class="tracy-inner nettrine-dbal">
		<?php if ($queries !== []): ?>
			<table class="tracy-sortable">
				<tr>
					<th>Time&nbsp;ms</th>
					<th>SQL</th>
				</tr>

				<?php foreach ($queries as $q): ?>
					<tr>
						<td>
							<?= sprintf('%0.2f', $q['duration'] * 1000); ?>
							<?php if (count($q['source']) !== 0): ?>
								<br><a class="tracy-toggle tracy-collapsed" data-tracy-ref="^tr .nettrine-dbal-backtrace"></a>
							<?php endif; ?>
						</td>
						<td class="tracy-dbal-sql">
							<?php $sql = $formatter->formatSql($connection, $q['sql'], $q['types'], $q['params']); ?>
							<?= QueryUtils::highlight($sql); ?>
							<?php if (count($q['source']) !== 0): ?>
								<table class="nettrine-dbal-backtrace tracy-collapsed">
									<?php foreach ($q['source'] as $s): ?>
										<tr><td><?= Helpers::editorLink($s['file'], $s['line']); ?></td></tr>
									<?php endforeach; ?>
								</table>
							<?php endif; ?>
						</td>
					</tr>
				<?php endforeach; ?>

			</table>
		<?php endif; ?>
	</div>
<?php } ?>
