<?php declare(strict_types = 1);

namespace Nettrine\DBAL\Tracy;

use Tracy\Dumper;

/** @var int $queriesNum */
/** @var int $totalTime */
/** @var array<array{sql: string, params: mixed[], types: mixed[], duration: float }> $queries */
?>
<style>
	#tracy-debug td.tracy-dbal-sql {
		background: white !important
	}

	#tracy-debug .tracy-dbal-source {
		color: #999 !important
	}

	#tracy-debug .tracy-dbal tr table {
		margin: 8px 0;
		max-height: 150px;
		overflow: auto
	}

	#tracy-debug .nettrine-dbal td > a.tracy-toggle::before {
		content: 'source';
	}
</style>

<?php if ($queriesNum === 0) { ?>
	<h1>No queries</h1>
<?php } else { ?>
	<h1>Queries:
		<?= $queriesNum ?>,
		time:
		<?= $totalTime ? sprintf('%0.3f', $totalTime * 1000) : ''; ?> ms
	</h1>
	<div class="tracy-inner nettrine-dbal">
		<?php if ($queries !== []): ?>
			<table class="tracy-sortable">
				<tr>
					<th>Time&nbsp;ms</th>
					<th>SQL</th>
					<th>Params</th>
				</tr>

				<?php foreach ($queries as $q): ?>
					<tr>
						<td>
							<?= sprintf('%0.2f', $q['duration'] * 1000); ?>
						</td>
						<td class="tracy-dbal-sql">
							<?= $q['sql']; ?>
						</td>
						<td class="tracy-dbal-sql">
							<?= Dumper::toHtml($q['params']); ?>
							<?= Dumper::toHtml($q['types'], [Dumper::COLLAPSE => true]); ?>
						</td>
					</tr>
				<?php endforeach; ?>

			</table>
		<?php endif; ?>
	</div>
<?php } ?>
