<?php declare(strict_types = 1);

namespace Nettrine\DBAL\Tracy;

use Doctrine\DBAL\Connection;
use Nettrine\DBAL\Utils\QueryUtils;
use Tracy\Dumper;
use Tracy\Helpers;

/** @var Connection $connection */
/** @var int $queriesNum */
/** @var int $totalTime */
/** @var string $connectionName */
/** @var array<array{fullsql: string, sql: string, params: mixed[], types: mixed[], duration: float, source: array<mixed> }> $queries */
?>
<style>
	#tracy-debug td.tracy-dbal-sql {
		background: white !important
	}

	#tracy-debug .tracy-dbal-source {
		color: #999 !important
	}

	#tracy-debug .tracy-dbal tr table {
		margin: 8px 0;
		max-height: 150px;
		overflow: auto
	}

	#tracy-debug .nettrine-dbal td > a.tracy-toggle::before {
		content: 'source';
	}
</style>

<?php if ($queriesNum === 0) { ?>
	<h1>No queries</h1>
<?php } else { ?>
	<h1>
		Connection: <?= $connectionName ?> (<?= ($connection->getParams()['driver'] ?? 'N/A') ?>)
	</h1>
	<h2>
		Queries: <?= $queriesNum ?>,
		time: <?= $totalTime ? sprintf('%0.3f', $totalTime * 1000) : ''; ?> ms
	</h2>
	<div class="tracy-inner nettrine-dbal">
		<div>
			<?= Dumper::toHtml($connectionParams, [Dumper::COLLAPSE => true]); ?>
		</div>

		<table class="tracy-sortable">
			<tr>
				<th>Time&nbsp;(ms)</th>
				<th>SQL</th>
				<th>Params</th>
				<th>Types</th>
			</tr>

			<?php foreach ($queries as $q): ?>
				<tr>
					<td>
						<?= sprintf('%0.2f', $q['duration'] * 1000); ?>
						<?php if (count($q['source']) !== 0): ?>
							<br><a class="tracy-toggle tracy-collapsed" data-tracy-ref="^tr .nettrine-dbal-backtrace"></a>
						<?php endif; ?>
					</td>
					<td class="tracy-dbal-sql">
						<?= QueryUtils::highlight($q['sql2']); ?>
						<?php if (count($q['source']) !== 0): ?>
							<table class="nettrine-dbal-backtrace tracy-collapsed">
								<?php foreach ($q['source'] as $s): ?>
									<tr>
										<td><?= Helpers::editorLink($s['file'], $s['line']); ?></td>
									</tr>
								<?php endforeach; ?>
							</table>
						<?php endif; ?>
					</td>
					<td class="tracy-dbal-sql">
						<?= Dumper::toHtml($q['params']); ?>
					</td>
					<td class="tracy-dbal-sql">
						<?= Dumper::toHtml($q['types'], [Dumper::COLLAPSE => true]); ?>
					</td>
				</tr>
			<?php endforeach; ?>
		</table>
	</div>
<?php } ?>
